USE roster_rocket_db;
DELETE FROM StudentCourses;
DELETE FROM Courses;
DELETE FROM Students;
DELETE FROM Users;
ALTER TABLE StudentCourses AUTO_INCREMENT = 1;
ALTER TABLE Courses AUTO_INCREMENT = 1;
ALTER TABLE Students AUTO_INCREMENT = 1;
ALTER TABLE Users AUTO_INCREMENT = 1;